### PR TITLE
Improve starting scripts and allow waiting config snmptrapd

### PR DESCRIPTION
**Pull request by agustinhenze**
### Use a different path for the snmptrapd.conf
   
Also, wait for the config is ready. The configuration can be generated by another process asynchronously.

### Wait for snmptrapd process before start filebeat

The processes are communicated through a named pipe and filebeat depends on snmptrapd be ready before reading from the pipe.

### CODE REVIEW

**Comment by neermitt** [comment]
@agustinhenze How about one more  process which restarts the `snmptrapd` on config file change? So that config can be updated once in configmap and all containers get the updated config file and results in restart of the `snmptrapd` process

**Review by rustycl0ck — APPROVED** [review]
💈

**Comment by rustycl0ck** [comment]
[Somehow] Do a dry-run config syntax validation before automatically restarting the pod, otherwise it'll go into `CrashloopBackOff` if there are any typos etc. in the config.

**Comment by agustinhenze** [comment]
> [Somehow] Do a dry-run config syntax validation before automatically restarting the pod, otherwise it'll go into `CrashloopBackOff` if there are any typos etc. in the config.

Yeah, I have tried something around that. Unfortunately snmptrapd doesn't support that, but I am planning a [Somehow]® way to do that in the config generator. Nice suggestion :)

**Pull request merged**
